// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: modules/control.proto

package modules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusTopics int32

const (
	BusTopics_CONTROL BusTopics = 0
	BusTopics_STATE   BusTopics = 1
)

// Enum value maps for BusTopics.
var (
	BusTopics_name = map[int32]string{
		0: "CONTROL",
		1: "STATE",
	}
	BusTopics_value = map[string]int32{
		"CONTROL": 0,
		"STATE":   1,
	}
)

func (x BusTopics) Enum() *BusTopics {
	p := new(BusTopics)
	*p = x
	return p
}

func (x BusTopics) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusTopics) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_control_proto_enumTypes[0].Descriptor()
}

func (BusTopics) Type() protoreflect.EnumType {
	return &file_modules_control_proto_enumTypes[0]
}

func (x BusTopics) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusTopics.Descriptor instead.
func (BusTopics) EnumDescriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_TYPE_UNSPECIFIED        MessageType = 0
	MessageType_TYPE_CURRENT_STATE      MessageType = 1
	MessageType_TYPE_CHANGE_STATE       MessageType = 2
	MessageType_TYPE_GET_CURRENT_STATES MessageType = 3
	MessageType_TYPE_GET_MANIFEST_REQ   MessageType = 4
	MessageType_TYPE_GET_MANIFEST_RESP  MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CURRENT_STATE",
		2: "TYPE_CHANGE_STATE",
		3: "TYPE_GET_CURRENT_STATES",
		4: "TYPE_GET_MANIFEST_REQ",
		5: "TYPE_GET_MANIFEST_RESP",
	}
	MessageType_value = map[string]int32{
		"TYPE_UNSPECIFIED":        0,
		"TYPE_CURRENT_STATE":      1,
		"TYPE_CHANGE_STATE":       2,
		"TYPE_GET_CURRENT_STATES": 3,
		"TYPE_GET_MANIFEST_REQ":   4,
		"TYPE_GET_MANIFEST_RESP":  5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_control_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_modules_control_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{1}
}

type ModuleState int32

const (
	ModuleState_UNSPECIFIED ModuleState = 0
	ModuleState_UNSTARTED   ModuleState = 1
	ModuleState_STARTED     ModuleState = 2
	ModuleState_STOPPED     ModuleState = 3
	ModuleState_FAILED      ModuleState = 4
	ModuleState_FINISHED    ModuleState = 5
)

// Enum value maps for ModuleState.
var (
	ModuleState_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNSTARTED",
		2: "STARTED",
		3: "STOPPED",
		4: "FAILED",
		5: "FINISHED",
	}
	ModuleState_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNSTARTED":   1,
		"STARTED":     2,
		"STOPPED":     3,
		"FAILED":      4,
		"FINISHED":    5,
	}
)

func (x ModuleState) Enum() *ModuleState {
	p := new(ModuleState)
	*p = x
	return p
}

func (x ModuleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleState) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_control_proto_enumTypes[2].Descriptor()
}

func (ModuleState) Type() protoreflect.EnumType {
	return &file_modules_control_proto_enumTypes[2]
}

func (x ModuleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleState.Descriptor instead.
func (ModuleState) EnumDescriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{2}
}

type CurrentModuleState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// string       module_name  = 2;
	ModuleState ModuleState `protobuf:"varint,3,opt,name=module_state,json=moduleState,proto3,enum=modules.ModuleState" json:"module_state,omitempty"`
}

func (x *CurrentModuleState) Reset() {
	*x = CurrentModuleState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentModuleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentModuleState) ProtoMessage() {}

func (x *CurrentModuleState) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentModuleState.ProtoReflect.Descriptor instead.
func (*CurrentModuleState) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentModuleState) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *CurrentModuleState) GetModuleState() ModuleState {
	if x != nil {
		return x.ModuleState
	}
	return ModuleState_UNSPECIFIED
}

type ChangeModuleState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// string       module_name  = 1;
	ModuleState ModuleState `protobuf:"varint,2,opt,name=module_state,json=moduleState,proto3,enum=modules.ModuleState" json:"module_state,omitempty"`
}

func (x *ChangeModuleState) Reset() {
	*x = ChangeModuleState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeModuleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeModuleState) ProtoMessage() {}

func (x *ChangeModuleState) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeModuleState.ProtoReflect.Descriptor instead.
func (*ChangeModuleState) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeModuleState) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ChangeModuleState) GetModuleState() ModuleState {
	if x != nil {
		return x.ModuleState
	}
	return ModuleState_UNSPECIFIED
}

type GetManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{2}
}

func (x *GetManifestRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type GetManifestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifest *Manifest `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

var File_modules_control_proto protoreflect.FileDescriptor

var file_modules_control_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x1a, 0x16, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x12, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x69, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x31, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0x44, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x08,
	0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2a, 0x23, 0x0a, 0x09, 0x42, 0x75, 0x73, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x01, 0x2a, 0xa6, 0x01,
	0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x55, 0x52, 0x52,
	0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x43,
	0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x53, 0x10, 0x03, 0x12,
	0x19, 0x0a, 0x15, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x4d, 0x41, 0x4e, 0x49,
	0x46, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x4d, 0x41, 0x4e, 0x49, 0x46, 0x45, 0x53, 0x54, 0x5f,
	0x52, 0x45, 0x53, 0x50, 0x10, 0x05, 0x2a, 0x61, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x46,
	0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x05, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f,
	0x75, 0x73, 0x6b, 0x6f, 0x69, 0x2f, 0x61, 0x6b, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_control_proto_rawDescOnce sync.Once
	file_modules_control_proto_rawDescData = file_modules_control_proto_rawDesc
)

func file_modules_control_proto_rawDescGZIP() []byte {
	file_modules_control_proto_rawDescOnce.Do(func() {
		file_modules_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_control_proto_rawDescData)
	})
	return file_modules_control_proto_rawDescData
}

var file_modules_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_modules_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modules_control_proto_goTypes = []any{
	(BusTopics)(0),              // 0: modules.BusTopics
	(MessageType)(0),            // 1: modules.MessageType
	(ModuleState)(0),            // 2: modules.ModuleState
	(*CurrentModuleState)(nil),  // 3: modules.CurrentModuleState
	(*ChangeModuleState)(nil),   // 4: modules.ChangeModuleState
	(*GetManifestRequest)(nil),  // 5: modules.GetManifestRequest
	(*GetManifestResponse)(nil), // 6: modules.GetManifestResponse
	(*Manifest)(nil),            // 7: modules.Manifest
}
var file_modules_control_proto_depIdxs = []int32{
	2, // 0: modules.CurrentModuleState.module_state:type_name -> modules.ModuleState
	2, // 1: modules.ChangeModuleState.module_state:type_name -> modules.ModuleState
	7, // 2: modules.GetManifestResponse.manifest:type_name -> modules.Manifest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_modules_control_proto_init() }
func file_modules_control_proto_init() {
	if File_modules_control_proto != nil {
		return
	}
	file_modules_manifest_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_modules_control_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CurrentModuleState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ChangeModuleState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetManifestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_control_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_control_proto_goTypes,
		DependencyIndexes: file_modules_control_proto_depIdxs,
		EnumInfos:         file_modules_control_proto_enumTypes,
		MessageInfos:      file_modules_control_proto_msgTypes,
	}.Build()
	File_modules_control_proto = out.File
	file_modules_control_proto_rawDesc = nil
	file_modules_control_proto_goTypes = nil
	file_modules_control_proto_depIdxs = nil
}
