// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: modules/control.proto

package modules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusTopics int32

const (
	BusTopics_MODULE_EVENT   BusTopics = 0
	BusTopics_MODULE_REQUEST BusTopics = 1
	BusTopics_MODULE_COMMAND BusTopics = 2
)

// Enum value maps for BusTopics.
var (
	BusTopics_name = map[int32]string{
		0: "MODULE_EVENT",
		1: "MODULE_REQUEST",
		2: "MODULE_COMMAND",
	}
	BusTopics_value = map[string]int32{
		"MODULE_EVENT":   0,
		"MODULE_REQUEST": 1,
		"MODULE_COMMAND": 2,
	}
)

func (x BusTopics) Enum() *BusTopics {
	p := new(BusTopics)
	*p = x
	return p
}

func (x BusTopics) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusTopics) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_control_proto_enumTypes[0].Descriptor()
}

func (BusTopics) Type() protoreflect.EnumType {
	return &file_modules_control_proto_enumTypes[0]
}

func (x BusTopics) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusTopics.Descriptor instead.
func (BusTopics) EnumDescriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{0}
}

type MessageTypeEvent int32

const (
	MessageTypeEvent_MODULE_CURRENT_STATE MessageTypeEvent = 0
)

// Enum value maps for MessageTypeEvent.
var (
	MessageTypeEvent_name = map[int32]string{
		0: "MODULE_CURRENT_STATE",
	}
	MessageTypeEvent_value = map[string]int32{
		"MODULE_CURRENT_STATE": 0,
	}
)

func (x MessageTypeEvent) Enum() *MessageTypeEvent {
	p := new(MessageTypeEvent)
	*p = x
	return p
}

func (x MessageTypeEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_control_proto_enumTypes[1].Descriptor()
}

func (MessageTypeEvent) Type() protoreflect.EnumType {
	return &file_modules_control_proto_enumTypes[1]
}

func (x MessageTypeEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeEvent.Descriptor instead.
func (MessageTypeEvent) EnumDescriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{1}
}

type MessageTypeRequest int32

const (
	MessageTypeRequest_MODULES_LIST_REQ  MessageTypeRequest = 0
	MessageTypeRequest_MODULES_LIST_RESP MessageTypeRequest = 1
)

// Enum value maps for MessageTypeRequest.
var (
	MessageTypeRequest_name = map[int32]string{
		0: "MODULES_LIST_REQ",
		1: "MODULES_LIST_RESP",
	}
	MessageTypeRequest_value = map[string]int32{
		"MODULES_LIST_REQ":  0,
		"MODULES_LIST_RESP": 1,
	}
)

func (x MessageTypeRequest) Enum() *MessageTypeRequest {
	p := new(MessageTypeRequest)
	*p = x
	return p
}

func (x MessageTypeRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_control_proto_enumTypes[2].Descriptor()
}

func (MessageTypeRequest) Type() protoreflect.EnumType {
	return &file_modules_control_proto_enumTypes[2]
}

func (x MessageTypeRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeRequest.Descriptor instead.
func (MessageTypeRequest) EnumDescriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{2}
}

type MessageTypeCommand int32

const (
	MessageTypeCommand_MODULE_AUTOSTART_SET_REQ  MessageTypeCommand = 0
	MessageTypeCommand_MODULE_AUTOSTART_SET_RESP MessageTypeCommand = 1
	MessageTypeCommand_MODULE_STATE_SET_REQ      MessageTypeCommand = 2
	MessageTypeCommand_MODULE_STATE_SET_RESP     MessageTypeCommand = 3
	MessageTypeCommand_MODULE_DETAIL_SET_REQ     MessageTypeCommand = 4
	MessageTypeCommand_MODULE_DETAIL_SET_RESP    MessageTypeCommand = 5
)

// Enum value maps for MessageTypeCommand.
var (
	MessageTypeCommand_name = map[int32]string{
		0: "MODULE_AUTOSTART_SET_REQ",
		1: "MODULE_AUTOSTART_SET_RESP",
		2: "MODULE_STATE_SET_REQ",
		3: "MODULE_STATE_SET_RESP",
		4: "MODULE_DETAIL_SET_REQ",
		5: "MODULE_DETAIL_SET_RESP",
	}
	MessageTypeCommand_value = map[string]int32{
		"MODULE_AUTOSTART_SET_REQ":  0,
		"MODULE_AUTOSTART_SET_RESP": 1,
		"MODULE_STATE_SET_REQ":      2,
		"MODULE_STATE_SET_RESP":     3,
		"MODULE_DETAIL_SET_REQ":     4,
		"MODULE_DETAIL_SET_RESP":    5,
	}
)

func (x MessageTypeCommand) Enum() *MessageTypeCommand {
	p := new(MessageTypeCommand)
	*p = x
	return p
}

func (x MessageTypeCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_control_proto_enumTypes[3].Descriptor()
}

func (MessageTypeCommand) Type() protoreflect.EnumType {
	return &file_modules_control_proto_enumTypes[3]
}

func (x MessageTypeCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeCommand.Descriptor instead.
func (MessageTypeCommand) EnumDescriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{3}
}

type ModuleState int32

const (
	ModuleState_UNSPECIFIED ModuleState = 0
	ModuleState_UNSTARTED   ModuleState = 1
	ModuleState_STARTED     ModuleState = 2
	ModuleState_STOPPED     ModuleState = 3
	ModuleState_FAILED      ModuleState = 4
	ModuleState_FINISHED    ModuleState = 5
)

// Enum value maps for ModuleState.
var (
	ModuleState_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNSTARTED",
		2: "STARTED",
		3: "STOPPED",
		4: "FAILED",
		5: "FINISHED",
	}
	ModuleState_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNSTARTED":   1,
		"STARTED":     2,
		"STOPPED":     3,
		"FAILED":      4,
		"FINISHED":    5,
	}
)

func (x ModuleState) Enum() *ModuleState {
	p := new(ModuleState)
	*p = x
	return p
}

func (x ModuleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleState) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_control_proto_enumTypes[4].Descriptor()
}

func (ModuleState) Type() protoreflect.EnumType {
	return &file_modules_control_proto_enumTypes[4]
}

func (x ModuleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleState.Descriptor instead.
func (ModuleState) EnumDescriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{4}
}

type ModuleCurrentStateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId    string      `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ModuleState ModuleState `protobuf:"varint,2,opt,name=module_state,json=moduleState,proto3,enum=modules.ModuleState" json:"module_state,omitempty"`
	Config      *Config     `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	StateDetail string      `protobuf:"bytes,4,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"`
}

func (x *ModuleCurrentStateEvent) Reset() {
	*x = ModuleCurrentStateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleCurrentStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleCurrentStateEvent) ProtoMessage() {}

func (x *ModuleCurrentStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleCurrentStateEvent.ProtoReflect.Descriptor instead.
func (*ModuleCurrentStateEvent) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleCurrentStateEvent) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleCurrentStateEvent) GetModuleState() ModuleState {
	if x != nil {
		return x.ModuleState
	}
	return ModuleState_UNSPECIFIED
}

func (x *ModuleCurrentStateEvent) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ModuleCurrentStateEvent) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

type ModuleListEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manifest *Manifest           `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	State    *CurrentModuleState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ModuleListEntry) Reset() {
	*x = ModuleListEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleListEntry) ProtoMessage() {}

func (x *ModuleListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleListEntry.ProtoReflect.Descriptor instead.
func (*ModuleListEntry) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleListEntry) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ModuleListEntry) GetState() *CurrentModuleState {
	if x != nil {
		return x.State
	}
	return nil
}

type ModulesListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModulesListRequest) Reset() {
	*x = ModulesListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModulesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulesListRequest) ProtoMessage() {}

func (x *ModulesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulesListRequest.ProtoReflect.Descriptor instead.
func (*ModulesListRequest) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{2}
}

type ModulesListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ModuleListEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *ModulesListResponse) Reset() {
	*x = ModulesListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModulesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulesListResponse) ProtoMessage() {}

func (x *ModulesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulesListResponse.ProtoReflect.Descriptor instead.
func (*ModulesListResponse) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{3}
}

func (x *ModulesListResponse) GetEntries() []*ModuleListEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ModuleAutostartSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId  string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Autostart bool   `protobuf:"varint,2,opt,name=autostart,proto3" json:"autostart,omitempty"`
}

func (x *ModuleAutostartSetRequest) Reset() {
	*x = ModuleAutostartSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleAutostartSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleAutostartSetRequest) ProtoMessage() {}

func (x *ModuleAutostartSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleAutostartSetRequest.ProtoReflect.Descriptor instead.
func (*ModuleAutostartSetRequest) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{4}
}

func (x *ModuleAutostartSetRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleAutostartSetRequest) GetAutostart() bool {
	if x != nil {
		return x.Autostart
	}
	return false
}

type ModuleAutostartSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModuleAutostartSetResponse) Reset() {
	*x = ModuleAutostartSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleAutostartSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleAutostartSetResponse) ProtoMessage() {}

func (x *ModuleAutostartSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleAutostartSetResponse.ProtoReflect.Descriptor instead.
func (*ModuleAutostartSetResponse) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{5}
}

type ModuleStateSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId string      `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	State    ModuleState `protobuf:"varint,2,opt,name=state,proto3,enum=modules.ModuleState" json:"state,omitempty"`
}

func (x *ModuleStateSetRequest) Reset() {
	*x = ModuleStateSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleStateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStateSetRequest) ProtoMessage() {}

func (x *ModuleStateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStateSetRequest.ProtoReflect.Descriptor instead.
func (*ModuleStateSetRequest) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{6}
}

func (x *ModuleStateSetRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleStateSetRequest) GetState() ModuleState {
	if x != nil {
		return x.State
	}
	return ModuleState_UNSPECIFIED
}

type ModuleStateSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModuleStateSetResponse) Reset() {
	*x = ModuleStateSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleStateSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStateSetResponse) ProtoMessage() {}

func (x *ModuleStateSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStateSetResponse.ProtoReflect.Descriptor instead.
func (*ModuleStateSetResponse) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{7}
}

type ModuleDetailSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId    string `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	StateDetail string `protobuf:"bytes,2,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"`
}

func (x *ModuleDetailSetRequest) Reset() {
	*x = ModuleDetailSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleDetailSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDetailSetRequest) ProtoMessage() {}

func (x *ModuleDetailSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDetailSetRequest.ProtoReflect.Descriptor instead.
func (*ModuleDetailSetRequest) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{8}
}

func (x *ModuleDetailSetRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleDetailSetRequest) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

type ModuleDetailSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModuleDetailSetResponse) Reset() {
	*x = ModuleDetailSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleDetailSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDetailSetResponse) ProtoMessage() {}

func (x *ModuleDetailSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDetailSetResponse.ProtoReflect.Descriptor instead.
func (*ModuleDetailSetResponse) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{9}
}

type CurrentModuleState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId    string      `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ModuleState ModuleState `protobuf:"varint,2,opt,name=module_state,json=moduleState,proto3,enum=modules.ModuleState" json:"module_state,omitempty"`
	Config      *Config     `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	StateDetail string      `protobuf:"bytes,4,opt,name=state_detail,json=stateDetail,proto3" json:"state_detail,omitempty"`
}

func (x *CurrentModuleState) Reset() {
	*x = CurrentModuleState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_control_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentModuleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentModuleState) ProtoMessage() {}

func (x *CurrentModuleState) ProtoReflect() protoreflect.Message {
	mi := &file_modules_control_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentModuleState.ProtoReflect.Descriptor instead.
func (*CurrentModuleState) Descriptor() ([]byte, []int) {
	return file_modules_control_proto_rawDescGZIP(), []int{10}
}

func (x *CurrentModuleState) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *CurrentModuleState) GetModuleState() ModuleState {
	if x != nil {
		return x.ModuleState
	}
	return ModuleState_UNSPECIFIED
}

func (x *CurrentModuleState) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CurrentModuleState) GetStateDetail() string {
	if x != nil {
		return x.StateDetail
	}
	return ""
}

var File_modules_control_proto protoreflect.FileDescriptor

var file_modules_control_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x1a, 0x14, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f,
	0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb,
	0x01, 0x0a, 0x17, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x73, 0x0a, 0x0f,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x2d, 0x0a, 0x08, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x31,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x14, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x13, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x22, 0x56, 0x0a, 0x19, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x6f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x75, 0x74, 0x6f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x15, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2a,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x58, 0x0a, 0x16, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x19,
	0x0a, 0x17, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x12, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x37, 0x0a,
	0x0c, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x2a, 0x45, 0x0a, 0x09, 0x42, 0x75, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12,
	0x10, 0x0a, 0x0c, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f,
	0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x10, 0x02, 0x2a, 0x2c, 0x0a, 0x10, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x14, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x2a, 0x41, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x10, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x53, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x53, 0x5f, 0x4c,
	0x49, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x2a, 0xbd, 0x01, 0x0a, 0x12, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x4f,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x00, 0x12,
	0x1d, 0x0a, 0x19, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x53, 0x54,
	0x41, 0x52, 0x54, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x12, 0x18,
	0x0a, 0x14, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53,
	0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x4f, 0x44, 0x55,
	0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x44, 0x45,
	0x54, 0x41, 0x49, 0x4c, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x04, 0x12, 0x1a,
	0x0a, 0x16, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x5f,
	0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x05, 0x2a, 0x61, 0x0a, 0x0b, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x05, 0x42, 0x29, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f,
	0x6e, 0x6f, 0x6d, 0x6f, 0x75, 0x73, 0x6b, 0x6f, 0x69, 0x2f, 0x61, 0x6b, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_control_proto_rawDescOnce sync.Once
	file_modules_control_proto_rawDescData = file_modules_control_proto_rawDesc
)

func file_modules_control_proto_rawDescGZIP() []byte {
	file_modules_control_proto_rawDescOnce.Do(func() {
		file_modules_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_control_proto_rawDescData)
	})
	return file_modules_control_proto_rawDescData
}

var file_modules_control_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_modules_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_modules_control_proto_goTypes = []any{
	(BusTopics)(0),                     // 0: modules.BusTopics
	(MessageTypeEvent)(0),              // 1: modules.MessageTypeEvent
	(MessageTypeRequest)(0),            // 2: modules.MessageTypeRequest
	(MessageTypeCommand)(0),            // 3: modules.MessageTypeCommand
	(ModuleState)(0),                   // 4: modules.ModuleState
	(*ModuleCurrentStateEvent)(nil),    // 5: modules.ModuleCurrentStateEvent
	(*ModuleListEntry)(nil),            // 6: modules.ModuleListEntry
	(*ModulesListRequest)(nil),         // 7: modules.ModulesListRequest
	(*ModulesListResponse)(nil),        // 8: modules.ModulesListResponse
	(*ModuleAutostartSetRequest)(nil),  // 9: modules.ModuleAutostartSetRequest
	(*ModuleAutostartSetResponse)(nil), // 10: modules.ModuleAutostartSetResponse
	(*ModuleStateSetRequest)(nil),      // 11: modules.ModuleStateSetRequest
	(*ModuleStateSetResponse)(nil),     // 12: modules.ModuleStateSetResponse
	(*ModuleDetailSetRequest)(nil),     // 13: modules.ModuleDetailSetRequest
	(*ModuleDetailSetResponse)(nil),    // 14: modules.ModuleDetailSetResponse
	(*CurrentModuleState)(nil),         // 15: modules.CurrentModuleState
	(*Config)(nil),                     // 16: modules.Config
	(*Manifest)(nil),                   // 17: modules.Manifest
}
var file_modules_control_proto_depIdxs = []int32{
	4,  // 0: modules.ModuleCurrentStateEvent.module_state:type_name -> modules.ModuleState
	16, // 1: modules.ModuleCurrentStateEvent.config:type_name -> modules.Config
	17, // 2: modules.ModuleListEntry.manifest:type_name -> modules.Manifest
	15, // 3: modules.ModuleListEntry.state:type_name -> modules.CurrentModuleState
	6,  // 4: modules.ModulesListResponse.entries:type_name -> modules.ModuleListEntry
	4,  // 5: modules.ModuleStateSetRequest.state:type_name -> modules.ModuleState
	4,  // 6: modules.CurrentModuleState.module_state:type_name -> modules.ModuleState
	16, // 7: modules.CurrentModuleState.config:type_name -> modules.Config
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_modules_control_proto_init() }
func file_modules_control_proto_init() {
	if File_modules_control_proto != nil {
		return
	}
	file_modules_config_proto_init()
	file_modules_manifest_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_modules_control_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ModuleCurrentStateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ModuleListEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ModulesListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ModulesListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ModuleAutostartSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ModuleAutostartSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ModuleStateSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ModuleStateSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ModuleDetailSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ModuleDetailSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_control_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CurrentModuleState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_control_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_control_proto_goTypes,
		DependencyIndexes: file_modules_control_proto_depIdxs,
		EnumInfos:         file_modules_control_proto_enumTypes,
		MessageInfos:      file_modules_control_proto_msgTypes,
	}.Build()
	File_modules_control_proto = out.File
	file_modules_control_proto_rawDesc = nil
	file_modules_control_proto_goTypes = nil
	file_modules_control_proto_depIdxs = nil
}
