// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: osc.proto

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OSCConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []*OSCTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *OSCConfig) Reset() {
	*x = OSCConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSCConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSCConfig) ProtoMessage() {}

func (x *OSCConfig) ProtoReflect() protoreflect.Message {
	mi := &file_osc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSCConfig.ProtoReflect.Descriptor instead.
func (*OSCConfig) Descriptor() ([]byte, []int) {
	return file_osc_proto_rawDescGZIP(), []int{0}
}

func (x *OSCConfig) GetTargets() []*OSCTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type OSCTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port    uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *OSCTarget) Reset() {
	*x = OSCTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSCTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSCTarget) ProtoMessage() {}

func (x *OSCTarget) ProtoReflect() protoreflect.Message {
	mi := &file_osc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSCTarget.ProtoReflect.Descriptor instead.
func (*OSCTarget) Descriptor() ([]byte, []int) {
	return file_osc_proto_rawDescGZIP(), []int{1}
}

func (x *OSCTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSCTarget) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OSCTarget) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type OSCValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*OSCValue_Nil
	//	*OSCValue_Int32
	//	*OSCValue_Float32
	//	*OSCValue_String_
	//	*OSCValue_Blob
	//	*OSCValue_Int64
	//	*OSCValue_True
	//	*OSCValue_False
	Value isOSCValue_Value `protobuf_oneof:"value"`
}

func (x *OSCValue) Reset() {
	*x = OSCValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSCValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSCValue) ProtoMessage() {}

func (x *OSCValue) ProtoReflect() protoreflect.Message {
	mi := &file_osc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSCValue.ProtoReflect.Descriptor instead.
func (*OSCValue) Descriptor() ([]byte, []int) {
	return file_osc_proto_rawDescGZIP(), []int{2}
}

func (m *OSCValue) GetValue() isOSCValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *OSCValue) GetNil() int32 {
	if x, ok := x.GetValue().(*OSCValue_Nil); ok {
		return x.Nil
	}
	return 0
}

func (x *OSCValue) GetInt32() int32 {
	if x, ok := x.GetValue().(*OSCValue_Int32); ok {
		return x.Int32
	}
	return 0
}

func (x *OSCValue) GetFloat32() float32 {
	if x, ok := x.GetValue().(*OSCValue_Float32); ok {
		return x.Float32
	}
	return 0
}

func (x *OSCValue) GetString_() string {
	if x, ok := x.GetValue().(*OSCValue_String_); ok {
		return x.String_
	}
	return ""
}

func (x *OSCValue) GetBlob() []byte {
	if x, ok := x.GetValue().(*OSCValue_Blob); ok {
		return x.Blob
	}
	return nil
}

func (x *OSCValue) GetInt64() int64 {
	if x, ok := x.GetValue().(*OSCValue_Int64); ok {
		return x.Int64
	}
	return 0
}

func (x *OSCValue) GetTrue() bool {
	if x, ok := x.GetValue().(*OSCValue_True); ok {
		return x.True
	}
	return false
}

func (x *OSCValue) GetFalse() bool {
	if x, ok := x.GetValue().(*OSCValue_False); ok {
		return x.False
	}
	return false
}

type isOSCValue_Value interface {
	isOSCValue_Value()
}

type OSCValue_Nil struct {
	Nil int32 `protobuf:"varint,1,opt,name=nil,proto3,oneof"`
}

type OSCValue_Int32 struct {
	Int32 int32 `protobuf:"varint,2,opt,name=int32,proto3,oneof"`
}

type OSCValue_Float32 struct {
	Float32 float32 `protobuf:"fixed32,3,opt,name=float32,proto3,oneof"`
}

type OSCValue_String_ struct {
	String_ string `protobuf:"bytes,4,opt,name=string,proto3,oneof"`
}

type OSCValue_Blob struct {
	Blob []byte `protobuf:"bytes,5,opt,name=blob,proto3,oneof"`
}

type OSCValue_Int64 struct {
	Int64 int64 `protobuf:"varint,6,opt,name=int64,proto3,oneof"`
}

type OSCValue_True struct {
	// int64    time     = 7;
	// int64    double   = 8;
	True bool `protobuf:"varint,9,opt,name=true,proto3,oneof"`
}

type OSCValue_False struct {
	False bool `protobuf:"varint,10,opt,name=false,proto3,oneof"`
}

func (*OSCValue_Nil) isOSCValue_Value() {}

func (*OSCValue_Int32) isOSCValue_Value() {}

func (*OSCValue_Float32) isOSCValue_Value() {}

func (*OSCValue_String_) isOSCValue_Value() {}

func (*OSCValue_Blob) isOSCValue_Value() {}

func (*OSCValue_Int64) isOSCValue_Value() {}

func (*OSCValue_True) isOSCValue_Value() {}

func (*OSCValue_False) isOSCValue_Value() {}

type OSCListTargetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OSCListTargetsRequest) Reset() {
	*x = OSCListTargetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSCListTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSCListTargetsRequest) ProtoMessage() {}

func (x *OSCListTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSCListTargetsRequest.ProtoReflect.Descriptor instead.
func (*OSCListTargetsRequest) Descriptor() ([]byte, []int) {
	return file_osc_proto_rawDescGZIP(), []int{3}
}

type OSCListTargetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []*OSCTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *OSCListTargetsResponse) Reset() {
	*x = OSCListTargetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSCListTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSCListTargetsResponse) ProtoMessage() {}

func (x *OSCListTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSCListTargetsResponse.ProtoReflect.Descriptor instead.
func (*OSCListTargetsResponse) Descriptor() ([]byte, []int) {
	return file_osc_proto_rawDescGZIP(), []int{4}
}

func (x *OSCListTargetsResponse) GetTargets() []*OSCTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type OSCSendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetName string      `protobuf:"bytes,1,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Address    string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Values     []*OSCValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *OSCSendMessageRequest) Reset() {
	*x = OSCSendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSCSendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSCSendMessageRequest) ProtoMessage() {}

func (x *OSCSendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSCSendMessageRequest.ProtoReflect.Descriptor instead.
func (*OSCSendMessageRequest) Descriptor() ([]byte, []int) {
	return file_osc_proto_rawDescGZIP(), []int{5}
}

func (x *OSCSendMessageRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *OSCSendMessageRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OSCSendMessageRequest) GetValues() []*OSCValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type OSCSendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OSCSendMessageResponse) Reset() {
	*x = OSCSendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSCSendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSCSendMessageResponse) ProtoMessage() {}

func (x *OSCSendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSCSendMessageResponse.ProtoReflect.Descriptor instead.
func (*OSCSendMessageResponse) Descriptor() ([]byte, []int) {
	return file_osc_proto_rawDescGZIP(), []int{6}
}

var File_osc_proto protoreflect.FileDescriptor

var file_osc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6f, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x76, 0x63,
	0x22, 0x35, 0x0a, 0x09, 0x4f, 0x53, 0x43, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x28, 0x0a,
	0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x4f, 0x53, 0x43, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0x4d, 0x0a, 0x09, 0x4f, 0x53, 0x43, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xd1, 0x01, 0x0a, 0x08, 0x4f, 0x53, 0x43, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x6e, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x03, 0x6e, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12,
	0x1a, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x00, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x12, 0x18, 0x0a, 0x06, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x12, 0x16, 0x0a, 0x05, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x04, 0x74, 0x72, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x66, 0x61, 0x6c,
	0x73, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x66, 0x61, 0x6c, 0x73,
	0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x4f, 0x53,
	0x43, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x16, 0x4f, 0x53, 0x43, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x4f, 0x53, 0x43, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0x79, 0x0a, 0x15, 0x4f, 0x53, 0x43, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x4f, 0x53, 0x43, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x4f, 0x53, 0x43, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e,
	0x6f, 0x6d, 0x6f, 0x75, 0x73, 0x6b, 0x6f, 0x69, 0x2f, 0x61, 0x6b, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x73, 0x76, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_osc_proto_rawDescOnce sync.Once
	file_osc_proto_rawDescData = file_osc_proto_rawDesc
)

func file_osc_proto_rawDescGZIP() []byte {
	file_osc_proto_rawDescOnce.Do(func() {
		file_osc_proto_rawDescData = protoimpl.X.CompressGZIP(file_osc_proto_rawDescData)
	})
	return file_osc_proto_rawDescData
}

var file_osc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_osc_proto_goTypes = []any{
	(*OSCConfig)(nil),              // 0: svc.OSCConfig
	(*OSCTarget)(nil),              // 1: svc.OSCTarget
	(*OSCValue)(nil),               // 2: svc.OSCValue
	(*OSCListTargetsRequest)(nil),  // 3: svc.OSCListTargetsRequest
	(*OSCListTargetsResponse)(nil), // 4: svc.OSCListTargetsResponse
	(*OSCSendMessageRequest)(nil),  // 5: svc.OSCSendMessageRequest
	(*OSCSendMessageResponse)(nil), // 6: svc.OSCSendMessageResponse
}
var file_osc_proto_depIdxs = []int32{
	1, // 0: svc.OSCConfig.targets:type_name -> svc.OSCTarget
	1, // 1: svc.OSCListTargetsResponse.targets:type_name -> svc.OSCTarget
	2, // 2: svc.OSCSendMessageRequest.values:type_name -> svc.OSCValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_osc_proto_init() }
func file_osc_proto_init() {
	if File_osc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_osc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OSCConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OSCTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OSCValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*OSCListTargetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OSCListTargetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OSCSendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*OSCSendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_osc_proto_msgTypes[2].OneofWrappers = []any{
		(*OSCValue_Nil)(nil),
		(*OSCValue_Int32)(nil),
		(*OSCValue_Float32)(nil),
		(*OSCValue_String_)(nil),
		(*OSCValue_Blob)(nil),
		(*OSCValue_Int64)(nil),
		(*OSCValue_True)(nil),
		(*OSCValue_False)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_osc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osc_proto_goTypes,
		DependencyIndexes: file_osc_proto_depIdxs,
		MessageInfos:      file_osc_proto_msgTypes,
	}.Build()
	File_osc_proto = out.File
	file_osc_proto_rawDesc = nil
	file_osc_proto_goTypes = nil
	file_osc_proto_depIdxs = nil
}
