// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: svc.proto

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNSPECIFIED                    MessageType = 0
	MessageType_HAS_TOPIC_REQ                  MessageType = 1
	MessageType_HAS_TOPIC_RESP                 MessageType = 2
	MessageType_SUBSCRIBE_REQ                  MessageType = 3
	MessageType_SUBSCRIBE_RESP                 MessageType = 4
	MessageType_UNSUBSCRIBE_REQ                MessageType = 5
	MessageType_UNSUBSCRIBE_RESP               MessageType = 6
	MessageType_KV_SET_REQ                     MessageType = 7
	MessageType_KV_SET_RESP                    MessageType = 8
	MessageType_KV_GET_REQ                     MessageType = 9
	MessageType_KV_GET_RESP                    MessageType = 10
	MessageType_KV_LIST_REQ                    MessageType = 11
	MessageType_KV_LIST_RESP                   MessageType = 12
	MessageType_KV_DELETE_REQ                  MessageType = 13
	MessageType_KV_DELETE_RESP                 MessageType = 14
	MessageType_LOG_SEND_REQ                   MessageType = 15
	MessageType_LOG_SEND_RESP                  MessageType = 16
	MessageType_WEBCLIENT_STATIC_DOWNLOAD_REQ  MessageType = 17
	MessageType_WEBCLIENT_STATIC_DOWNLOAD_RESP MessageType = 18
	MessageType_TEMPLATE_RENDER_REQ            MessageType = 19
	MessageType_TEMPLATE_RENDER_RESP           MessageType = 20
	MessageType_TIME_NOTIFICATION_EVENT        MessageType = 21
	MessageType_TIME_NOTIFICATION_REQ          MessageType = 22
	MessageType_TIME_NOTIFICATION_RESP         MessageType = 23
	MessageType_TIME_STOP_NOTIFICATION_REQ     MessageType = 24
	MessageType_TIME_STOP_NOTIFICATION_RESP    MessageType = 25
	MessageType_TIME_CURRENT_REQ               MessageType = 26
	MessageType_TIME_CURRENT_RESP              MessageType = 27
	MessageType_WEBCLIENT_HTTP_REQ             MessageType = 28
	MessageType_WEBCLIENT_HTTP_RESP            MessageType = 29
	MessageType_OSC_LIST_TARGETS_REQ           MessageType = 30
	MessageType_OSC_LIST_TARGETS_RESP          MessageType = 31
	MessageType_OSC_SEND_MESSAGE_REQ           MessageType = 32
	MessageType_OSC_SEND_MESSAGE_RESP          MessageType = 33
	MessageType_WEBHOOK_CALL_EVENT             MessageType = 34
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "HAS_TOPIC_REQ",
		2:  "HAS_TOPIC_RESP",
		3:  "SUBSCRIBE_REQ",
		4:  "SUBSCRIBE_RESP",
		5:  "UNSUBSCRIBE_REQ",
		6:  "UNSUBSCRIBE_RESP",
		7:  "KV_SET_REQ",
		8:  "KV_SET_RESP",
		9:  "KV_GET_REQ",
		10: "KV_GET_RESP",
		11: "KV_LIST_REQ",
		12: "KV_LIST_RESP",
		13: "KV_DELETE_REQ",
		14: "KV_DELETE_RESP",
		15: "LOG_SEND_REQ",
		16: "LOG_SEND_RESP",
		17: "WEBCLIENT_STATIC_DOWNLOAD_REQ",
		18: "WEBCLIENT_STATIC_DOWNLOAD_RESP",
		19: "TEMPLATE_RENDER_REQ",
		20: "TEMPLATE_RENDER_RESP",
		21: "TIME_NOTIFICATION_EVENT",
		22: "TIME_NOTIFICATION_REQ",
		23: "TIME_NOTIFICATION_RESP",
		24: "TIME_STOP_NOTIFICATION_REQ",
		25: "TIME_STOP_NOTIFICATION_RESP",
		26: "TIME_CURRENT_REQ",
		27: "TIME_CURRENT_RESP",
		28: "WEBCLIENT_HTTP_REQ",
		29: "WEBCLIENT_HTTP_RESP",
		30: "OSC_LIST_TARGETS_REQ",
		31: "OSC_LIST_TARGETS_RESP",
		32: "OSC_SEND_MESSAGE_REQ",
		33: "OSC_SEND_MESSAGE_RESP",
		34: "WEBHOOK_CALL_EVENT",
	}
	MessageType_value = map[string]int32{
		"UNSPECIFIED":                    0,
		"HAS_TOPIC_REQ":                  1,
		"HAS_TOPIC_RESP":                 2,
		"SUBSCRIBE_REQ":                  3,
		"SUBSCRIBE_RESP":                 4,
		"UNSUBSCRIBE_REQ":                5,
		"UNSUBSCRIBE_RESP":               6,
		"KV_SET_REQ":                     7,
		"KV_SET_RESP":                    8,
		"KV_GET_REQ":                     9,
		"KV_GET_RESP":                    10,
		"KV_LIST_REQ":                    11,
		"KV_LIST_RESP":                   12,
		"KV_DELETE_REQ":                  13,
		"KV_DELETE_RESP":                 14,
		"LOG_SEND_REQ":                   15,
		"LOG_SEND_RESP":                  16,
		"WEBCLIENT_STATIC_DOWNLOAD_REQ":  17,
		"WEBCLIENT_STATIC_DOWNLOAD_RESP": 18,
		"TEMPLATE_RENDER_REQ":            19,
		"TEMPLATE_RENDER_RESP":           20,
		"TIME_NOTIFICATION_EVENT":        21,
		"TIME_NOTIFICATION_REQ":          22,
		"TIME_NOTIFICATION_RESP":         23,
		"TIME_STOP_NOTIFICATION_REQ":     24,
		"TIME_STOP_NOTIFICATION_RESP":    25,
		"TIME_CURRENT_REQ":               26,
		"TIME_CURRENT_RESP":              27,
		"WEBCLIENT_HTTP_REQ":             28,
		"WEBCLIENT_HTTP_RESP":            29,
		"OSC_LIST_TARGETS_REQ":           30,
		"OSC_LIST_TARGETS_RESP":          31,
		"OSC_SEND_MESSAGE_REQ":           32,
		"OSC_SEND_MESSAGE_RESP":          33,
		"WEBHOOK_CALL_EVENT":             34,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_svc_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_svc_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{0}
}

type HasTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic     string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	TimeoutMs int32  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
}

func (x *HasTopicRequest) Reset() {
	*x = HasTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasTopicRequest) ProtoMessage() {}

func (x *HasTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasTopicRequest.ProtoReflect.Descriptor instead.
func (*HasTopicRequest) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{0}
}

func (x *HasTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *HasTopicRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type HasTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic    string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	HasTopic bool   `protobuf:"varint,2,opt,name=has_topic,json=hasTopic,proto3" json:"has_topic,omitempty"`
}

func (x *HasTopicResponse) Reset() {
	*x = HasTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasTopicResponse) ProtoMessage() {}

func (x *HasTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasTopicResponse.ProtoReflect.Descriptor instead.
func (*HasTopicResponse) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{1}
}

func (x *HasTopicResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *HasTopicResponse) GetHasTopic() bool {
	if x != nil {
		return x.HasTopic
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{3}
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{5}
}

type KVSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KVSetRequest) Reset() {
	*x = KVSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSetRequest) ProtoMessage() {}

func (x *KVSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSetRequest.ProtoReflect.Descriptor instead.
func (*KVSetRequest) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{6}
}

func (x *KVSetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KVSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KVSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KVSetResponse) Reset() {
	*x = KVSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSetResponse) ProtoMessage() {}

func (x *KVSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSetResponse.ProtoReflect.Descriptor instead.
func (*KVSetResponse) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{7}
}

type KVGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *KVGetRequest) Reset() {
	*x = KVGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetRequest) ProtoMessage() {}

func (x *KVGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetRequest.ProtoReflect.Descriptor instead.
func (*KVGetRequest) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{8}
}

func (x *KVGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type KVGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KVGetResponse) Reset() {
	*x = KVGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetResponse) ProtoMessage() {}

func (x *KVGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetResponse.ProtoReflect.Descriptor instead.
func (*KVGetResponse) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{9}
}

func (x *KVGetResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KVGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KVListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *KVListRequest) Reset() {
	*x = KVListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVListRequest) ProtoMessage() {}

func (x *KVListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVListRequest.ProtoReflect.Descriptor instead.
func (*KVListRequest) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{10}
}

func (x *KVListRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *KVListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *KVListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KVListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys         [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Prefix       []byte   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	TotalMatches uint32   `protobuf:"varint,3,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	Offset       uint32   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit        uint32   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *KVListResponse) Reset() {
	*x = KVListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVListResponse) ProtoMessage() {}

func (x *KVListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVListResponse.ProtoReflect.Descriptor instead.
func (*KVListResponse) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{11}
}

func (x *KVListResponse) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KVListResponse) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *KVListResponse) GetTotalMatches() uint32 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

func (x *KVListResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *KVListResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KVDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *KVDeleteRequest) Reset() {
	*x = KVDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDeleteRequest) ProtoMessage() {}

func (x *KVDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDeleteRequest.ProtoReflect.Descriptor instead.
func (*KVDeleteRequest) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{12}
}

func (x *KVDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type KVDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KVDeleteResponse) Reset() {
	*x = KVDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDeleteResponse) ProtoMessage() {}

func (x *KVDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDeleteResponse.ProtoReflect.Descriptor instead.
func (*KVDeleteResponse) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{13}
}

type WebhookValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *WebhookValues) Reset() {
	*x = WebhookValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookValues) ProtoMessage() {}

func (x *WebhookValues) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookValues.ProtoReflect.Descriptor instead.
func (*WebhookValues) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{14}
}

func (x *WebhookValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type WebhookCallEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params map[string]*WebhookValues `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *WebhookCallEvent) Reset() {
	*x = WebhookCallEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookCallEvent) ProtoMessage() {}

func (x *WebhookCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_svc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookCallEvent.ProtoReflect.Descriptor instead.
func (*WebhookCallEvent) Descriptor() ([]byte, []int) {
	return file_svc_proto_rawDescGZIP(), []int{15}
}

func (x *WebhookCallEvent) GetParams() map[string]*WebhookValues {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_svc_proto protoreflect.FileDescriptor

var file_svc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x76, 0x63,
	0x22, 0x46, 0x0a, 0x0f, 0x48, 0x61, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x22, 0x45, 0x0a, 0x10, 0x48, 0x61, 0x73, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x22,
	0x28, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a,
	0x0a, 0x12, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x6e,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x36, 0x0a, 0x0c, 0x4b, 0x56, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x4b, 0x56, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x0a, 0x0c, 0x4b, 0x56,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x0d,
	0x4b, 0x56, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x55, 0x0a, 0x0d, 0x4b, 0x56, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x8f, 0x01, 0x0a,
	0x0e, 0x4b, 0x56, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x23, 0x0a, 0x0d, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x23,
	0x0a, 0x0f, 0x4b, 0x56, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x4b, 0x56, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x57, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x9c, 0x01, 0x0a, 0x10, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43, 0x61, 0x6c, 0x6c,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x57, 0x65, 0x62, 0x68,
	0x6f, 0x6f, 0x6b, 0x43, 0x61, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x1a, 0x4d, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a,
	0xb7, 0x06, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x48, 0x41, 0x53, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x41, 0x53, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x55, 0x42, 0x53, 0x43,
	0x52, 0x49, 0x42, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x55,
	0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x04, 0x12, 0x13,
	0x0a, 0x0f, 0x55, 0x4e, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49,
	0x42, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x56, 0x5f,
	0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x56, 0x5f,
	0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x08, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x56,
	0x5f, 0x47, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x09, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x56,
	0x5f, 0x47, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x4b,
	0x56, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0b, 0x12, 0x10, 0x0a, 0x0c,
	0x4b, 0x56, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x0c, 0x12, 0x11,
	0x0a, 0x0d, 0x4b, 0x56, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10,
	0x0d, 0x12, 0x12, 0x0a, 0x0e, 0x4b, 0x56, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x52,
	0x45, 0x53, 0x50, 0x10, 0x0e, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x4e,
	0x44, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0f, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x4f, 0x47, 0x5f, 0x53,
	0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x10, 0x12, 0x21, 0x0a, 0x1d, 0x57, 0x45,
	0x42, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x43, 0x5f, 0x44,
	0x4f, 0x57, 0x4e, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x11, 0x12, 0x22, 0x0a,
	0x1e, 0x57, 0x45, 0x42, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x49,
	0x43, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10,
	0x12, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45,
	0x4e, 0x44, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x13, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x45,
	0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x52, 0x45,
	0x53, 0x50, 0x10, 0x14, 0x12, 0x1b, 0x0a, 0x17, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4e, 0x4f, 0x54,
	0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10,
	0x15, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x16, 0x12, 0x1a, 0x0a, 0x16,
	0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x17, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x49, 0x4d, 0x45,
	0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x18, 0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x49, 0x4d, 0x45,
	0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x19, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x49, 0x4d,
	0x45, 0x5f, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x1a, 0x12,
	0x15, 0x0a, 0x11, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x5f,
	0x52, 0x45, 0x53, 0x50, 0x10, 0x1b, 0x12, 0x16, 0x0a, 0x12, 0x57, 0x45, 0x42, 0x43, 0x4c, 0x49,
	0x45, 0x4e, 0x54, 0x5f, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x1c, 0x12, 0x17,
	0x0a, 0x13, 0x57, 0x45, 0x42, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x48, 0x54, 0x54, 0x50,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x1d, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x53, 0x43, 0x5f, 0x4c,
	0x49, 0x53, 0x54, 0x5f, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x53, 0x5f, 0x52, 0x45, 0x51, 0x10,
	0x1e, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x53, 0x43, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x54, 0x41,
	0x52, 0x47, 0x45, 0x54, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x1f, 0x12, 0x18, 0x0a, 0x14,
	0x4f, 0x53, 0x43, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x5f, 0x52, 0x45, 0x51, 0x10, 0x20, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x53, 0x43, 0x5f, 0x53, 0x45,
	0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10,
	0x21, 0x12, 0x16, 0x0a, 0x12, 0x57, 0x45, 0x42, 0x48, 0x4f, 0x4f, 0x4b, 0x5f, 0x43, 0x41, 0x4c,
	0x4c, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x22, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f,
	0x75, 0x73, 0x6b, 0x6f, 0x69, 0x2f, 0x61, 0x6b, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x76, 0x63,
	0x2f, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_proto_rawDescOnce sync.Once
	file_svc_proto_rawDescData = file_svc_proto_rawDesc
)

func file_svc_proto_rawDescGZIP() []byte {
	file_svc_proto_rawDescOnce.Do(func() {
		file_svc_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_proto_rawDescData)
	})
	return file_svc_proto_rawDescData
}

var file_svc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_svc_proto_goTypes = []any{
	(MessageType)(0),            // 0: svc.MessageType
	(*HasTopicRequest)(nil),     // 1: svc.HasTopicRequest
	(*HasTopicResponse)(nil),    // 2: svc.HasTopicResponse
	(*SubscribeRequest)(nil),    // 3: svc.SubscribeRequest
	(*SubscribeResponse)(nil),   // 4: svc.SubscribeResponse
	(*UnsubscribeRequest)(nil),  // 5: svc.UnsubscribeRequest
	(*UnsubscribeResponse)(nil), // 6: svc.UnsubscribeResponse
	(*KVSetRequest)(nil),        // 7: svc.KVSetRequest
	(*KVSetResponse)(nil),       // 8: svc.KVSetResponse
	(*KVGetRequest)(nil),        // 9: svc.KVGetRequest
	(*KVGetResponse)(nil),       // 10: svc.KVGetResponse
	(*KVListRequest)(nil),       // 11: svc.KVListRequest
	(*KVListResponse)(nil),      // 12: svc.KVListResponse
	(*KVDeleteRequest)(nil),     // 13: svc.KVDeleteRequest
	(*KVDeleteResponse)(nil),    // 14: svc.KVDeleteResponse
	(*WebhookValues)(nil),       // 15: svc.WebhookValues
	(*WebhookCallEvent)(nil),    // 16: svc.WebhookCallEvent
	nil,                         // 17: svc.WebhookCallEvent.ParamsEntry
}
var file_svc_proto_depIdxs = []int32{
	17, // 0: svc.WebhookCallEvent.params:type_name -> svc.WebhookCallEvent.ParamsEntry
	15, // 1: svc.WebhookCallEvent.ParamsEntry.value:type_name -> svc.WebhookValues
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_svc_proto_init() }
func file_svc_proto_init() {
	if File_svc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HasTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HasTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UnsubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UnsubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*KVSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*KVSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*KVGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*KVGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*KVListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*KVListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*KVDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*KVDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*WebhookValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*WebhookCallEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svc_proto_goTypes,
		DependencyIndexes: file_svc_proto_depIdxs,
		EnumInfos:         file_svc_proto_enumTypes,
		MessageInfos:      file_svc_proto_msgTypes,
	}.Build()
	File_svc_proto = out.File
	file_svc_proto_rawDesc = nil
	file_svc_proto_goTypes = nil
	file_svc_proto_depIdxs = nil
}
